BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        BoxLayout:
            orientation: 'vertical'
            TextInput:
                text: '34'
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert miles to km'
    Label:
        text: 'test'
